### ISSUE TITLE
Treated as datetime 12121212

### ISSUE THREAD

**Issue by aantonbor** [wiztools/xsd-gen#12]
Exception: cvc-datatype-valid.1.2.1: '12121212' is not a valid value for 'dateTime'.

However -><CusomerACCTNumber>12121212</CusomerACCTNumber> results in schema file as <xsd:element name="CusomerACCTNumber" minOccurs="0" type="xsd:dateTime"/> ?

**Comment by subwiz** [comment]
I'm able to reproduce. There is an issue in the regex I had taken from the internet back then. Working on it.
