### ISSUE TITLE
Release plan?

### ISSUE THREAD

**Issue by albertotn** [wiztools/xsd-gen#13]
Hi! I'm looking forward this library and I want to know which kind of release plan do you have for a stable version, any idea? I think some explanation on wiki or readme could help.
Thanks!

**Comment by subwiz** [comment]
We do not have a defined release plan as of now. When users report issues / give pull requests, I fix them. If it is a substantial fix, I release new version, else, I wait for a good amount of smaller fixes to accumulate before giving out a release.
