### ISSUE TITLE
4 digit values interpreted as date time

### ISSUE THREAD

**Issue by wkalkus** [wiztools/xsd-gen#14]
Examples of wrongfully intepreted values from xml:
<imageWidth>1200</imageWidth>
<publicationYear>2012</publicationYear>
<imageHeight>1983</imageHeight>
<id>3373</id>

When there are more digits it is properly intepreted as integer.

**Comment by subwiz** [comment]
Could be related to #12.

**Comment by subwiz** [comment]
Fixed.

**Comment by subwiz** [comment]
A minor release is also done: https://jitpack.io/#wiztools/xsd-gen/0.2.4
