### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by fyudanov** [wiztools/xsd-gen#18]
Hi @subwiz.

It looks like this repository is missing open source license reference. 
This make it problematic to fork and reuse the code in big corporation projects.

According to this manifest I believe, it wasn't your intention:
https://www.wiztools.org/tenets.html

Wouldn't it make it difficult to you to add some license reference (e.g MIT) to this github repository?

Thanks a lot!

**Comment by subwiz** [comment]
MIT license added.

**Comment by fyudanov** [comment]
Thanks!
